# Generated by Django 6.0.7 on 2026-07-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Xizmat sarlavhasi')),
                ('description', models.TextField(verbose_name='Xizmat tavsifi')),
                ('icon_class', models.CharField(blank=True, help_text='Masalan: bi bi-dribbble, bi bi-file-earmark-text, bi bi-speedometer2, bi bi-layers', max_length=100, null=True, verbose_name='Ikonka classi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ismi va familiyasi')),
                ('position', models.CharField(max_length=100, verbose_name='Lavozimi')),
                ('bio', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('image', models.ImageField(upload_to='team/', verbose_name='Rasmi')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter linki')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook linki')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram linki')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn linki')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'zolari",
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
