# Generated by Django 6.0.7 on 2026-07-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_service_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=40)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
