# Generated by Django 6.0.7 on 2026-07-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_murojaat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojaat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
