# Generated by Django 6.0.7 on 2026-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_murojaat_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='murojaat',
            options={'ordering': ['-date'], 'verbose_name': 'Murojaat', 'verbose_name_plural': 'Murojaat'},
        ),
    ]
