# Generated by Django 6.0.7 on 2026-07-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_subscribe_alter_murojaat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
